export interface App {
  id: string
  name: string
  developer: string
  icon: string
  category: string
  brewCask: string
  isPaid?: boolean
}

export interface Category {
  id: string
  name: string
  count: number
}

export const categories: Category[] = [
  { id: "internet", name: "Internet", count: 11 },
  { id: "productivity", name: "Productivity", count: 16 },
  { id: "developer", name: "Developer", count: 26 },
  { id: "tools", name: "Tools", count: 22 },
  { id: "utilities", name: "Utilities", count: 21 },
  { id: "multimedia", name: "Multimedia", count: 15 },
  { id: "messaging", name: "Messaging", count: 9 },
]

export const apps: App[] = [
  // Internet (11 apps)
  {
    id: "firefox",
    name: "Firefox",
    developer: "Mozilla",
    icon: "firefox",
    category: "internet",
    brewCask: "firefox",
  },
  {
    id: "firefox-dev",
    name: "Firefox Dev.",
    developer: "Mozilla",
    icon: "firefox",
    category: "internet",
    brewCask: "firefox-developer-edition",
    isPaid: false,
  },
  {
    id: "chrome",
    name: "Chrome",
    developer: "Google",
    icon: "chrome",
    category: "internet",
    brewCask: "google-chrome",
  },
  {
    id: "chromium",
    name: "Chromium",
    developer: "Chromium Prj.",
    icon: "chromium",
    category: "internet",
    brewCask: "chromium",
  },
  {
    id: "chrome-canary",
    name: "Chrome Canary",
    developer: "Google",
    icon: "chrome",
    category: "internet",
    brewCask: "google-chrome-canary",
  },
  {
    id: "brave",
    name: "Brave",
    developer: "Brave Software, Inc.",
    icon: "brave",
    category: "internet",
    brewCask: "brave-browser",
  },
  {
    id: "vivaldi",
    name: "Vivaldi",
    developer: "Vivaldi Technologies",
    icon: "vivaldi",
    category: "internet",
    brewCask: "vivaldi",
  },
  {
    id: "tor-browser",
    name: "TorBrowser",
    developer: "Tor Prj.",
    icon: "tor",
    category: "internet",
    brewCask: "tor-browser",
  },
  {
    id: "sleipnir",
    name: "Sleipnir",
    developer: "Fenrir Inc.",
    icon: "sleipnir",
    category: "internet",
    brewCask: "sleipnir",
  },
  {
    id: "yandex",
    name: "Yandex",
    developer: "Yandex",
    icon: "yandex",
    category: "internet",
    brewCask: "yandex",
  },
  {
    id: "unison",
    name: "Unison 2",
    developer: "Panic",
    icon: "unison",
    category: "internet",
    brewCask: "unison",
  },

  // Productivity (16 apps)
  {
    id: "evernote",
    name: "Evernote",
    developer: "Evernote",
    icon: "evernote",
    category: "productivity",
    brewCask: "evernote",
  },
  {
    id: "atext",
    name: "aText",
    developer: "aText",
    icon: "atext",
    category: "productivity",
    brewCask: "atext",
    isPaid: true,
  },
  {
    id: "bettertouchtool",
    name: "BetterTouchTool",
    developer: "Andreas Hegenberg",
    icon: "bettertouchtool",
    category: "productivity",
    brewCask: "bettertouchtool",
  },
  {
    id: "omnifocus",
    name: "OmniFocus",
    developer: "Omni Group",
    icon: "omnifocus",
    category: "productivity",
    brewCask: "omnifocus",
    isPaid: true,
  },
  {
    id: "dropbox",
    name: "Dropbox",
    developer: "Dropbox",
    icon: "dropbox",
    category: "productivity",
    brewCask: "dropbox",
  },
  {
    id: "google-drive",
    name: "Drive",
    developer: "Google",
    icon: "googledrive",
    category: "productivity",
    brewCask: "google-drive",
  },
  {
    id: "resilio-sync",
    name: "Sync",
    developer: "Resilio",
    icon: "resilio",
    category: "productivity",
    brewCask: "resilio-sync",
    isPaid: true,
  },
  {
    id: "megasync",
    name: "MEGAsync",
    developer: "Mega Ltd.",
    icon: "mega",
    category: "productivity",
    brewCask: "megasync",
  },
  {
    id: "openoffice",
    name: "OpenOffice",
    developer: "Apache",
    icon: "openoffice",
    category: "productivity",
    brewCask: "openoffice",
  },
  {
    id: "libreoffice",
    name: "LibreOffice",
    developer: "Document Fdn.",
    icon: "libreoffice",
    category: "productivity",
    brewCask: "libreoffice",
  },
  {
    id: "alfred",
    name: "Alfred 3",
    developer: "Running with Crayons",
    icon: "alfred",
    category: "productivity",
    brewCask: "alfred",
  },
  {
    id: "quicksilver",
    name: "Quicksilver",
    developer: "Quicksilver Team",
    icon: "quicksilver",
    category: "productivity",
    brewCask: "quicksilver",
  },
  {
    id: "carbon-copy-cloner",
    name: "CCC",
    developer: "Bombich",
    icon: "ccc",
    category: "productivity",
    brewCask: "carbon-copy-cloner",
    isPaid: true,
  },
  {
    id: "superduper",
    name: "SuperDuper!",
    developer: "Shirt Pocket",
    icon: "superduper",
    category: "productivity",
    brewCask: "superduper",
  },
  {
    id: "hyperswitch",
    name: "HyperSwitch",
    developer: "Christian Baumgart",
    icon: "hyperswitch",
    category: "productivity",
    brewCask: "hyperswitch",
    isPaid: true,
  },
  {
    id: "fantastical",
    name: "Fantastical",
    developer: "Flexibits",
    icon: "fantastical",
    category: "productivity",
    brewCask: "fantastical",
    isPaid: true,
  },

  // Developer (26 apps)
  {
    id: "github-desktop",
    name: "GitHub",
    developer: "GitHub",
    icon: "github",
    category: "developer",
    brewCask: "github",
  },
  {
    id: "sourcetree",
    name: "SourceTree",
    developer: "Atlassian",
    icon: "sourcetree",
    category: "developer",
    brewCask: "sourcetree",
  },
  {
    id: "sequel-pro",
    name: "SequelPro",
    developer: "SequelPro Team",
    icon: "sequelpro",
    category: "developer",
    brewCask: "sequel-pro",
  },
  {
    id: "robo-3t",
    name: "Robo 3T",
    developer: "Paralect",
    icon: "robo3t",
    category: "developer",
    brewCask: "robo-3t",
  },
  {
    id: "nova",
    name: "Nova",
    developer: "Panic, Inc.",
    icon: "nova",
    category: "developer",
    brewCask: "nova",
    isPaid: true,
  },
  {
    id: "brackets",
    name: "Brackets",
    developer: "Brackets Team",
    icon: "brackets",
    category: "developer",
    brewCask: "brackets",
  },
  {
    id: "sublime-text",
    name: "SublimeText",
    developer: "Sublime HQ Pty",
    icon: "sublime",
    category: "developer",
    brewCask: "sublime-text",
    isPaid: true,
  },
  {
    id: "atom",
    name: "Atom",
    developer: "GitHub",
    icon: "atom",
    category: "developer",
    brewCask: "atom",
    isPaid: true,
  },
  {
    id: "android-studio",
    name: "Android Std",
    developer: "Google",
    icon: "androidstudio",
    category: "developer",
    brewCask: "android-studio",
  },
  {
    id: "pycharm-ce",
    name: "PyCharm CE",
    developer: "JetBrains",
    icon: "pycharm",
    category: "developer",
    brewCask: "pycharm-ce",
  },
  {
    id: "dash",
    name: "Dash",
    developer: "Kapeli",
    icon: "dash",
    category: "developer",
    brewCask: "dash",
    isPaid: true,
  },
  {
    id: "espresso",
    name: "Espresso",
    developer: "MacRabit",
    icon: "espresso",
    category: "developer",
    brewCask: "espresso",
    isPaid: true,
  },
  {
    id: "processing",
    name: "Processing",
    developer: "Processing",
    icon: "processing",
    category: "developer",
    brewCask: "processing",
  },
  {
    id: "arduino",
    name: "Arduino",
    developer: "Arduino",
    icon: "arduino",
    category: "developer",
    brewCask: "arduino",
  },
  {
    id: "poedit",
    name: "Poedit",
    developer: "Vaclav Slavik",
    icon: "poedit",
    category: "developer",
    brewCask: "poedit",
  },
  {
    id: "macvim",
    name: "MacVim",
    developer: "MacVim Team",
    icon: "macvim",
    category: "developer",
    brewCask: "macvim",
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    developer: "Microsoft",
    icon: "vscode",
    category: "developer",
    brewCask: "visual-studio-code",
  },
  {
    id: "intellij-idea-ce",
    name: "IntelliJ IDEA CE",
    developer: "JetBrains",
    icon: "intellij",
    category: "developer",
    brewCask: "intellij-idea-ce",
  },
  {
    id: "docker",
    name: "Docker",
    developer: "Docker Inc.",
    icon: "docker",
    category: "developer",
    brewCask: "docker",
  },
  {
    id: "sketch",
    name: "Sketch",
    developer: "Bohemian BV",
    icon: "sketch",
    category: "developer",
    brewCask: "sketch",
    isPaid: true,
  },
  {
    id: "postman",
    name: "Postman",
    developer: "Postdot Tech. Inc.",
    icon: "postman",
    category: "developer",
    brewCask: "postman",
  },
  {
    id: "zeplin",
    name: "Zeplin",
    developer: "Zeplin Inc.",
    icon: "zeplin",
    category: "developer",
    brewCask: "zeplin",
    isPaid: true,
  },
  {
    id: "insomnia",
    name: "Insomnia",
    developer: "Kong, Inc.",
    icon: "insomnia",
    category: "developer",
    brewCask: "insomnia",
  },
  {
    id: "phpstorm",
    name: "PhpStorm",
    developer: "JetBrains",
    icon: "phpstorm",
    category: "developer",
    brewCask: "phpstorm",
  },
  {
    id: "bbedit",
    name: "BBEdit",
    developer: "Bare Bones",
    icon: "bbedit",
    category: "developer",
    brewCask: "bbedit",
    isPaid: true,
  },
  {
    id: "gitkraken",
    name: "GitKraken",
    developer: "Axosoft",
    icon: "gitkraken",
    category: "developer",
    brewCask: "gitkraken",
  },

  // Tools (22 apps)
  {
    id: "iterm2",
    name: "iTerm2",
    developer: "George Nachman",
    icon: "iterm",
    category: "tools",
    brewCask: "iterm2",
  },
  {
    id: "transmission",
    name: "Transmission",
    developer: "Mitchell Livingston",
    icon: "transmission",
    category: "tools",
    brewCask: "transmission",
  },
  {
    id: "cord",
    name: "CoRD",
    developer: "CoRD Team",
    icon: "cord",
    category: "tools",
    brewCask: "cord",
  },
  {
    id: "keka",
    name: "Keka",
    developer: "aONe",
    icon: "keka",
    category: "tools",
    brewCask: "keka",
  },
  {
    id: "the-unarchiver",
    name: "The Unarchiver",
    developer: "Dag Agren",
    icon: "unarchiver",
    category: "tools",
    brewCask: "the-unarchiver",
  },
  {
    id: "1password",
    name: "1Password",
    developer: "AgileBits",
    icon: "1password",
    category: "tools",
    brewCask: "1password",
    isPaid: true,
  },
  {
    id: "nordpass",
    name: "NordPass",
    developer: "Nord Security",
    icon: "nordpass",
    category: "tools",
    brewCask: "nordpass",
  },
  {
    id: "filezilla",
    name: "FileZilla",
    developer: "FileZilla Prj.",
    icon: "filezilla",
    category: "tools",
    brewCask: "filezilla",
  },
  {
    id: "transmit",
    name: "Transmit",
    developer: "Panic, Inc.",
    icon: "transmit",
    category: "tools",
    brewCask: "transmit",
    isPaid: true,
  },
  {
    id: "cyberduck",
    name: "Cyberduck",
    developer: "Cyberduck Team",
    icon: "cyberduck",
    category: "tools",
    brewCask: "cyberduck",
  },
  {
    id: "viscosity",
    name: "Viscosity",
    developer: "Sparklabs",
    icon: "viscosity",
    category: "tools",
    brewCask: "viscosity",
    isPaid: true,
  },
  {
    id: "skim",
    name: "Skim",
    developer: "Skim Team",
    icon: "skim",
    category: "tools",
    brewCask: "skim",
  },
  {
    id: "fluid",
    name: "Fluid",
    developer: "CelestialTeapot",
    icon: "fluid",
    category: "tools",
    brewCask: "fluid",
  },
  {
    id: "keepassx",
    name: "KeePassX",
    developer: "KeePassX Team",
    icon: "keepassx",
    category: "tools",
    brewCask: "keepassx",
  },
  {
    id: "tunnelblick",
    name: "Tunnelblick",
    developer: "Tunnelblick Team",
    icon: "tunnelblick",
    category: "tools",
    brewCask: "tunnelblick",
  },
  {
    id: "teamviewer-qs",
    name: "TeamViewerQS",
    developer: "TeamViewer",
    icon: "teamviewer",
    category: "tools",
    brewCask: "teamviewer-quicksupport",
  },
  {
    id: "forklift",
    name: "ForkLift",
    developer: "BinaryNights",
    icon: "forklift",
    category: "tools",
    brewCask: "forklift",
    isPaid: true,
  },
  {
    id: "jump-desktop",
    name: "JumpDesktop",
    developer: "PhaseFive Systems",
    icon: "jumpdesktop",
    category: "tools",
    brewCask: "jump-desktop-connect",
    isPaid: true,
  },
  {
    id: "exodus",
    name: "Exodus",
    developer: "Exodus",
    icon: "exodus",
    category: "tools",
    brewCask: "exodus",
  },
  {
    id: "shimo",
    name: "Shimo",
    developer: "Mailbutler GmbH",
    icon: "shimo",
    category: "tools",
    brewCask: "shimo",
    isPaid: true,
  },
  {
    id: "desktime",
    name: "DeskTime",
    developer: "Draugiem Group",
    icon: "desktime",
    category: "tools",
    brewCask: "desktime",
  },
  {
    id: "etcher",
    name: "Etcher",
    developer: "Resin.io",
    icon: "etcher",
    category: "tools",
    brewCask: "balenaetcher",
  },

  // Utilities (21 apps)
  {
    id: "clamxav",
    name: "ClamXAV",
    developer: "Canimaan Software",
    icon: "clamxav",
    category: "utilities",
    brewCask: "clamxav",
  },
  {
    id: "appcleaner",
    name: "AppCleaner",
    developer: "FreeMacSoft",
    icon: "appcleaner",
    category: "utilities",
    brewCask: "appcleaner",
  },
  {
    id: "ccleaner",
    name: "CCleaner",
    developer: "Piriform",
    icon: "ccleaner",
    category: "utilities",
    brewCask: "ccleaner",
  },
  {
    id: "trim-enabler",
    name: "Trim Enabler",
    developer: "Cindori Software",
    icon: "trimenabler",
    category: "utilities",
    brewCask: "trim-enabler",
  },
  {
    id: "coconutbattery",
    name: "coconutBattery",
    developer: "Coconut Flavour",
    icon: "coconutbattery",
    category: "utilities",
    brewCask: "coconutbattery",
  },
  {
    id: "flux",
    name: "Flux",
    developer: "f.lux Team",
    icon: "flux",
    category: "utilities",
    brewCask: "flux",
  },
  {
    id: "cdock",
    name: "cDock",
    developer: "cDock Team",
    icon: "cdock",
    category: "utilities",
    brewCask: "cdock",
  },
  {
    id: "bartender",
    name: "Bartender",
    developer: "Surtees Studios",
    icon: "bartender",
    category: "utilities",
    brewCask: "bartender",
    isPaid: true,
  },
  {
    id: "istat-menus",
    name: "iStat Menus",
    developer: "Bjango",
    icon: "istatmenus",
    category: "utilities",
    brewCask: "istat-menus",
    isPaid: true,
  },
  {
    id: "mactracker",
    name: "Mactracker",
    developer: "Ian Page",
    icon: "mactracker",
    category: "utilities",
    brewCask: "mactracker",
  },
  {
    id: "gyazo",
    name: "Gyazo",
    developer: "Nota Inc.",
    icon: "gyazo",
    category: "utilities",
    brewCask: "gyazo",
  },
  {
    id: "gyazo-gif",
    name: "Gyazo GIF",
    developer: "Nota Inc.",
    icon: "gyazo",
    category: "utilities",
    brewCask: "gyazo-gif",
  },
  {
    id: "unetbootin",
    name: "UNetbootin",
    developer: "Geza Kovacs",
    icon: "unetbootin",
    category: "utilities",
    brewCask: "unetbootin",
  },
  {
    id: "spectacle",
    name: "Spectacle",
    developer: "Eric Czarny",
    icon: "spectacle",
    category: "utilities",
    brewCask: "spectacle",
  },
  {
    id: "cleanmymac",
    name: "CleanMyMac",
    developer: "MacPaw",
    icon: "cleanmymac",
    category: "utilities",
    brewCask: "cleanmymac",
    isPaid: true,
  },
  {
    id: "gemini",
    name: "Gemini",
    developer: "MacPaw",
    icon: "gemini",
    category: "utilities",
    brewCask: "gemini",
    isPaid: true,
  },
  {
    id: "daisydisk",
    name: "DaisyDisk",
    developer: "Sw. Ambience",
    icon: "daisydisk",
    category: "utilities",
    brewCask: "daisydisk",
    isPaid: true,
  },
  {
    id: "duet",
    name: "Duet",
    developer: "Kairos",
    icon: "duet",
    category: "utilities",
    brewCask: "duet",
  },
  {
    id: "malwarebytes",
    name: "Anti-Malware",
    developer: "Malwarebytes",
    icon: "malwarebytes",
    category: "utilities",
    brewCask: "malwarebytes",
  },
  {
    id: "diskmaker-x",
    name: "DiskMaker X 9",
    developer: "DiskMaker Team",
    icon: "diskmaker",
    category: "utilities",
    brewCask: "diskmaker-x",
    isPaid: true,
  },
  {
    id: "macpilot",
    name: "MacPilot",
    developer: "Koingo Soft",
    icon: "macpilot",
    category: "utilities",
    brewCask: "macpilot",
    isPaid: true,
  },

  // Multimedia (15 apps)
  {
    id: "spotify",
    name: "Spotify",
    developer: "Spotify",
    icon: "spotify",
    category: "multimedia",
    brewCask: "spotify",
  },
  {
    id: "vlc",
    name: "VLC",
    developer: "VideoLAN",
    icon: "vlc",
    category: "multimedia",
    brewCask: "vlc",
  },
  {
    id: "mpv",
    name: "mpv",
    developer: "mpv Team",
    icon: "mpv",
    category: "multimedia",
    brewCask: "mpv",
    isPaid: true,
  },
  {
    id: "boom",
    name: "Boom 2",
    developer: "Global Delight Tech.",
    icon: "boom",
    category: "multimedia",
    brewCask: "boom",
    isPaid: true,
  },
  {
    id: "openemu",
    name: "OpenEmu",
    developer: "OpenEmu Team",
    icon: "openemu",
    category: "multimedia",
    brewCask: "openemu",
  },
  {
    id: "calibre",
    name: "Calibre",
    developer: "Kovid Goyal",
    icon: "calibre",
    category: "multimedia",
    brewCask: "calibre",
  },
  {
    id: "inkscape",
    name: "Inkscape",
    developer: "Inkscape Team",
    icon: "inkscape",
    category: "multimedia",
    brewCask: "inkscape",
  },
  {
    id: "gimp",
    name: "GIMP",
    developer: "GIMP Team",
    icon: "gimp",
    category: "multimedia",
    brewCask: "gimp",
  },
  {
    id: "steam",
    name: "Steam",
    developer: "Valve",
    icon: "steam",
    category: "multimedia",
    brewCask: "steam",
  },
  {
    id: "kodi",
    name: "Kodi",
    developer: "Kodi Team",
    icon: "kodi",
    category: "multimedia",
    brewCask: "kodi",
  },
  {
    id: "plex",
    name: "Plex",
    developer: "Plex, Inc.",
    icon: "plex",
    category: "multimedia",
    brewCask: "plex",
  },
  {
    id: "handbrake",
    name: "HandBrake",
    developer: "HandBrake Team",
    icon: "handbrake",
    category: "multimedia",
    brewCask: "handbrake",
  },
  {
    id: "burn",
    name: "Burn",
    developer: "Burn Team",
    icon: "burn",
    category: "multimedia",
    brewCask: "burn",
  },
  {
    id: "vox",
    name: "VOX Player",
    developer: "Coppertino Inc.",
    icon: "vox",
    category: "multimedia",
    brewCask: "vox",
  },
  {
    id: "iina",
    name: "IINA",
    developer: "The IINA Team",
    icon: "iina",
    category: "multimedia",
    brewCask: "iina",
  },

  // Messaging (9 apps)
  {
    id: "skype",
    name: "Skype",
    developer: "Microsoft",
    icon: "skype",
    category: "messaging",
    brewCask: "skype",
  },
  {
    id: "telegram",
    name: "Telegram",
    developer: "Telegram",
    icon: "telegram",
    category: "messaging",
    brewCask: "telegram",
  },
  {
    id: "thunderbird",
    name: "Thunderbird",
    developer: "Mozilla",
    icon: "thunderbird",
    category: "messaging",
    brewCask: "thunderbird",
  },
  {
    id: "postbox",
    name: "Postbox",
    developer: "Postbox, Inc.",
    icon: "postbox",
    category: "messaging",
    brewCask: "postbox",
    isPaid: true,
  },
  {
    id: "adium",
    name: "Adium",
    developer: "Adium Team",
    icon: "adium",
    category: "messaging",
    brewCask: "adium",
  },
  {
    id: "jitsi",
    name: "Jitsi",
    developer: "Jitsi Team",
    icon: "jitsi",
    category: "messaging",
    brewCask: "jitsi-meet",
  },
  {
    id: "slack",
    name: "Slack",
    developer: "Slack",
    icon: "slack",
    category: "messaging",
    brewCask: "slack",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    developer: "WhatsApp Inc.",
    icon: "whatsapp",
    category: "messaging",
    brewCask: "whatsapp",
  },
  {
    id: "discord",
    name: "Discord",
    developer: "Discord Inc.",
    icon: "discord",
    category: "messaging",
    brewCask: "discord",
  },
]

export function generateInstallCommand(selectedApps: App[]): string {
  if (selectedApps.length === 0) return ""

  const casks = selectedApps.map((app) => app.brewCask)

  if (casks.length === 0) return ""

  return `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash && brew install --cask ${casks.join(" ")}`
}
